/*
 * This program generates a random string with a length of 8 characters.
 */
package misc;
import java.io.*;
import java.util.Random;
/**
 * @author fazer
 */
public class password_generator extends javax.swing.JFrame {
   
    BufferedReader hi = new BufferedReader (new InputStreamReader (System.in));
    char one, two, three, four, five, six, seven, eight, nine, ten;
    char array[] = {one, two, three, four, five, six, seven, eight};
    String password = new String(array);
    public password_generator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OutputPane = new javax.swing.JTextPane();
        Generatebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OutputPane.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                OutputPaneComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(OutputPane);

        Generatebutton.setText("Generate");
        Generatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(Generatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Generatebutton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneratebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratebuttonActionPerformed
        
        String xyz = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%&*";
        
        Random r = new Random();
        
        one = xyz.charAt(r.nextInt(xyz.length()));
        two = xyz.charAt(r.nextInt(xyz.length()));
        three = xyz.charAt(r.nextInt(xyz.length()));
        four = xyz.charAt(r.nextInt(xyz.length()));
        five = xyz.charAt(r.nextInt(xyz.length()));
        six = xyz.charAt(r.nextInt(xyz.length()));
        seven = xyz.charAt(r.nextInt(xyz.length()));
        eight = xyz.charAt(r.nextInt(xyz.length()));
        nine = xyz.charAt(r.nextInt(xyz.length()));
        ten = xyz.charAt(r.nextInt(xyz.length()));
        
        char array[] = {one, two, three, four, five, six, seven, eight, nine, ten};
        
        String password = new String(array);
        
        OutputPane.setText(password);
    }//GEN-LAST:event_GeneratebuttonActionPerformed

    private void OutputPaneComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_OutputPaneComponentAdded
        OutputPane.setText(password);
    }//GEN-LAST:event_OutputPaneComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(password_generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new password_generator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generatebutton;
    private javax.swing.JTextPane OutputPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
